name: Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: umidbekk/actions/prepare-node-repo@v2
        with:
          node-version: "16"

      - run: npx tsc
      - run: npm run lint
      - run: npm run format -- --no-write
      - run: npm run cover
      - uses: codecov/codecov-action@v3.1.0

  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [14, 16, 18]

    steps:
      - uses: umidbekk/actions/prepare-node-repo@v2
        with:
          node-version: ${{ matrix.node }}

      - run: npm run e2e

      - if: failure()
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: ignore
          name: build-examples-${{ matrix.os }}-${{ matrix.node }}-
          path: |
            examples/*/dist
            test/errors/*/dist
