name: Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: "14"

      - run: npm ci
      - run: npx tsc
      - run: npm run lint
      - run: npm run format -- --no-write
      - run: npm run cover
      - uses: codecov/codecov-action@v2.0.3

  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [12, 14, 16]

    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "npm"
          node-version: ${{ matrix.node }}

      - if: ${{ matrix.node == '12' }}
        run: npm i -g npm@7

      - run: npm ci
      - run: npm run e2e
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          if-no-files-found: ignore
          name: build-examples-${{ matrix.os }}-${{ matrix.node }}-
          path: |
            examples/*/dist
            test/errors/*/dist
