name: Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: avocadowastaken/actions/prepare-node-repo@v2
        with:
          node-version: 16
      - run: npm run checks
      - uses: codecov/codecov-action@v3.1.1

  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [14, 16, 18]

    steps:
      - uses: avocadowastaken/actions/prepare-node-repo@v2
        with:
          node-version: ${{ matrix.node }}

      - run: npm run e2e

      - if: failure()
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: ignore
          name: build-examples-${{ matrix.os }}-${{ matrix.node }}-
          path: |
            examples/*/dist
            test/errors/*/dist
