name: Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
      - uses: actions/checkout@v2
      - uses: umidbekk/actions/npm/install@v1

      - run: yarn tsc
      - run: yarn lint
      - run: yarn format --check

  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [12, 14, 16]

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/checkout@v2
      - uses: umidbekk/actions/npm/install@v1
        with:
          cache-key: npm-${{ matrix.os }}-${{ matrix.node }}-

      - run: yarn test
      - uses: codecov/codecov-action@v1
        if: matrix.os == 'ubuntu-latest' && matrix.node == '12'
